environment:
  matrix:
    - nodejs_version: "20"
    - nodejs_version: "22"
    - nodejs_version: "24"
    - nodejs_version: "" # latest

install:
  - ps: "Install-Product node $env:nodejs_version"
  - "npm install"

test_script:
  - "node --version"
  - "npm --version"
  - "npm test"

build: off
